# Emojilang uses the duodecimal numeral system, also known as base 12
<digit> ::= "🕛" | "🕐" | "🕑" | "🕒" | "🕓" | "🕔" | "🕕" | "🕖" | "🕗" | "🕘" | "🕙" | "🕚"
<integer> ::= <digit> | <integer><digit>

# Emojilang uses an alphabet containing some emojis
<letter> ::= "😡" | "🥵" | "🥶" | "😨" | "🥱" | "😈" | "👿" | "🤢" | "🤡" | "💩" | "💀"
<variable> ::= <letter> | <variable><letter> | <variable><digit>

# Arithmetics
<expr> ::= <term> | <expr>"😀"<term> | <expr> "☹️" <term>
<term> ::= <term>"😂"<factor> | <term>"😭"<factor> | <factor>
<factor> ::= "("<expr>")" | "☹️"<factor> | <integer> | <variable>

# Other